name: First GitHub Actionrrrr

on:
  push:
    branches:
      - main 

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from GitHubrrr Actions"
