name: Pehli git action-23

on:
  push:
    branches:
      - main
jobs:
  myjob:
    name: its-first-job
    runs-on: ubuntu-latest   
    steps: 
    - name: Print hello world
      run: echo "Hello ,wassup"
        